apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: paizhicheng-management
  name: paizhicheng-management
  namespace: paizhicheng
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: paizhicheng-management   # 前端Deployment的选择器标签改为"olympic-frontend"
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: paizhicheng-management  # 前端Deployment的标签改为"olympic-frontend"
    spec:
      imagePullSecrets:
        - name: aliyun
      containers:
        - image: $REGISTRY/$DOCKERHUB_NAMESPACE/paizhicheng-management:latest
          imagePullPolicy: Always
          name: paizhicheng-management  # 前端容器的名称改为"olympic-frontend"
          ports:
            - name: http-admin
              containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: '3'
              memory: 3000Mi
            requests:
              cpu: 60m
              memory: 50Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: paizhicheng-backend  # 后端Deployment的标签改为"olympic-backend"
  name: paizhicheng-backend  # 后端Deployment的名称改为"olympic-backend"
  namespace: paizhicheng
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: paizhicheng-backend  # 后端Deployment的选择器标签改为"olympic-backend"
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: paizhicheng-backend  # 后端Deployment的标签改为"olympic-backend"
    spec:
      imagePullSecrets:
        - name: aliyun
      containers:
        - image: $REGISTRY/$DOCKERHUB_NAMESPACE/paizhicheng-backend:latest
          imagePullPolicy: Always
          name: paizhicheng-backend  # 后端容器的名称改为"olympic-backend"
          ports:
            - name: http-admin2
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: '3'
              memory: 3000Mi
            requests:
              cpu: 60m
              memory: 50Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: paizhicheng
  name: paizhicheng-management-service
  namespace: paizhicheng
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: paizhicheng-management
  sessionAffinity: None
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: paizhicheng
  name: paizhicheng-backend-service
  namespace: paizhicheng
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: paizhicheng-backend
  sessionAffinity: None
  type: ClusterIP
