version: '2.0'
services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    command: redis-server --requirepass 123456

  tdengine:
    container_name: tdengine
    image: tdengine/tdengine:3.0.7.1
    hostname: td1
    ports:
      - 6030-6049:6030-6049/tcp
      - 6030-6049:6030-6049/udp
    volumes:
      - /mnt/hiwoo/tdengine/etc/taos:/etc/taos
      - /mnt/hiwoo/tdengine/var/log/taos:/var/log/taos
      - /mnt/hiwoo/tdengine/var/lib/taos:/var/lib/taos
    restart: always

  nginx:
    container_name: nginx
    image: nginx:1.17.7
    ports:
      - 80:80
      - 443:443
    volumes:
      - /mnt/hiwoo/nginx/html:/usr/share/nginx/html
      - /mnt/hiwoo/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /mnt/hiwoo/nginx/logs:/var/log/nginx
      - /mnt/hiwoo/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - /mnt/hiwoo/nginx/cert:/etc/nginx/cert
      - /mnt/hiwoo/platformImgs:/mnt/hiwoo/platformImgs
    restart: always

  emqx:
    container_name: emqx
    image: emqx:5.0
    ports:
      - 18083:18083
      - 1883:1883
      - 8084:8084
      - 8883:8883
      - 8083:8083
    restart: always



